//------------------------------------------------------------------
// EasyLanguage Code for Tradestation / MultiCharts of EW_H1_860122146
//
//   Generated by StrategyQuant X Build 144
//   at 06/16/2026 11:27
//  
//   Backtested on @EW / H1, 2009.01.02 - 2020.03.06 
//
//   Generated for Main chart = Current Symbol / Current TF;
//------------------------------------------------------------------
[IntrabarOrderGeneration = false]

inputs:
	// Strategy variables
	MagicNumber(11111),
	ADXLowerPeriod1(14),
	ADXChangesUpPeriod1(20),
	PriceEntryMult1(1.4),
	ProfitTarget1(300),
	StopLoss1(70),

	// Trading Options
    
	DontTradeOnWeekends(false),
	FridayCloseTime(0038),
	SundayOpenTime(0038),	
	ExitAtEndOfDay(false),
	DayExitTime(1500),    
	ExitOnFriday(true),
	FridayExitTime(1430),
	LimitSignalsTimeRange(false),
	SignalTimeRangeFrom(0800),
	SignalTimeRangeTo(1600),
	ExitAtEndOfRange(false),
	OrderTypeToExit(0),
	LimitMaxDistanceFromMarket(false),  // Limit max order price distance from market
	MaxDistancePct(6),  // Maximum distance from market price in %
	MaxTradesPerDay(0),
	MinimumSL(0),  // Minimum SL in ticks/pips, 0 means unlimited
	MaximumSL(0),  // Maximum SL in ticks/pips, 0 means unlimited
	MinimumPT(0),  // Minimum PT in ticks/pips, 0 means unlimited
	MaximumPT(0),  // Maximum PT in ticks/pips, 0 means unlimited	
	UseInitialStopLoss(false),  // Sets StopLoss immediately after the order gets filled. Otherwise SL is set on next bar.
    // Template for a trading option /TradingOptions/LimitOver_variables.tpl missing, ignoring!


	// Money Management - Fixed size
	mmLots(1.0),
    double mmMultiplier(1.0),
	InitialCapital(10000);

vars:
	// Internal variables
	LongEntrySignal(false),
	ShortEntrySignal(false),
	LongExitSignal(false),
	ShortExitSignal(false),
	NumberOfSharesLong(0),NumberOfSharesShort(0),
	tickSize(MinMove/PriceScale),
	OpenOrdersAllowed(true),
	IntPriceLevel(0),IntPriceLevelLong(0),IntPriceLevelShort(0),IntLongSL(0),IntShortSL(0),IntPT(0),
	IntLongTS(0),IntShortTS(0),
	IntLongBE(0),IntShortBE(0),
	InitDone(false),
	LongSLPlaced(false),ShortSLPlaced(false),
   OrderSize(0),
   RemainingSize(0),
   ATMExitPrice(0);

	Array: bool cond[100](false);
   


// =================================================================
// TRADING OPTIONS LOGIC
// =================================================================
OpenOrdersAllowed = true;

// Dont trade on weekends
if DontTradeOnWeekends then begin
	if DayOfWeek(Date) = 5 then begin
		if FridayCloseTime <> 0000 and Time >= FridayCloseTime then begin
			OpenOrdersAllowed = False;
		end;	
	end
	else if DayOfWeek(Date) = 6 then begin
		OpenOrdersAllowed = False;
	end
	else if DayOfWeek(Date) = 0 and Time < SundayOpenTime then begin
		OpenOrdersAllowed = False;
	end; 
end;

// Exit on close (end of day)
if ExitAtEndOfDay then begin
	if DayExitTime <> 0000 then begin 
		if LimitSignalsTimeRange = False then begin 
		 	if Time >= DayExitTime then begin 
				if (MarketPosition > 0) then Sell("ExitEndOfDayL1") This Bar On Close;
				if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS1") This Bar On Close;
				OpenOrdersAllowed = False;
			end;
		end;
		if LimitSignalsTimeRange = True then begin
			if Time >= DayExitTime and Time < SignalTimeRangeFrom then begin
				if (MarketPosition > 0) then Sell("ExitEndOfDayL2") This Bar On Close;
				if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS2") This Bar On Close; 
				OpenOrdersAllowed = False;
			end;
			if DayExitTime >= SignalTimeRangeFrom and  SignalTimeRangeFrom < SignalTimeRangeTo then begin
				if Time >= DayExitTime and Time >= SignalTimeRangeFrom then begin
					if (MarketPosition > 0) then Sell("ExitEndOfDayL3") This Bar On Close;
					if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS3") This Bar On Close;
					OpenOrdersAllowed = False;
				end;
			end;
		end;
	end
	else SetExitOnClose;
end;


// Exit on Friday
if ExitOnFriday then begin
	if DayOfWeek(Date) = 5 then begin
		if FridayExitTime <> 0000 and Time >= FridayExitTime then begin
			if (MarketPosition > 0) then Sell("ExitFridayL") This Bar On Close;
			if (MarketPosition < 0) then BuyToCover("ExitFridayS") This Bar On Close;
			OpenOrdersAllowed = False;
		end;
	end
	else if DayOfWeek(Date) = 6 then begin
		OpenOrdersAllowed = False;
	end; 
end;

// Limit time range
if(OpenOrdersAllowed = True and LimitSignalsTimeRange = True and ((SignalTimeRangeFrom < SignalTimeRangeTo and (Time < SignalTimeRangeFrom or Time >= SignalTimeRangeTo)) or 
									   (SignalTimeRangeFrom >= SignalTimeRangeTo and (Time < SignalTimeRangeFrom and Time >= SignalTimeRangeTo)))
) then OpenOrdersAllowed = False;


// Exit At End Of Range
if LimitSignalsTimeRange = True and ExitAtEndOfRange = true then begin
	if SignalTimeRangeFrom < SignalTimeRangeTo and Time >= SignalTimeRangeTo then begin
		if (MarketPosition > 0) then Sell("ExitEndOfRangeL1") This Bar On Close;
		if (MarketPosition < 0) then BuyToCover("ExitEndOfRangeS1") This Bar On Close;
	end;
	if SignalTimeRangeFrom >= SignalTimeRangeTo and Time >= SignalTimeRangeTo and Time < SignalTimeRangeFrom then begin
		if (MarketPosition > 0) then Sell("ExitEndOfRangeL2") This Bar On Close;
		if (MarketPosition < 0) then BuyToCover("ExitEndOfRangeS2") This Bar On Close;
	end;
end;


// Max trades per day
if(OpenOrdersAllowed = True and MaxTradesPerDay <> 0 and EntriesToday(Date) >= MaxTradesPerDay) then
	OpenOrdersAllowed = False;
// Template for a trading option /TradingOptions/LimitOver_code.tpl missing, ignoring!
    
    

// =================================================================
// TRADING RULES LOGIC
// =================================================================
               
//------------------------------------------------------------------
// Rule: Trading signals
//------------------------------------------------------------------
Value1= SQ_ADX_R(ADXLowerPeriod1, 0, 1)[2];
Value2= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3+2];
Value3= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3+1];
Value4= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3];
LongEntrySignal = ((Value1<20) and (Value2 > Value3 and Value3 < Value4));


Value1= SQ_ADX_R(ADXLowerPeriod1, 0, 1)[2];
Value2= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3+2];
Value3= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3+1];
Value4= SQ_ADX_R(ADXChangesUpPeriod1, 0, 1)[3];
ShortEntrySignal = ((Value1<20) and (Value2 > Value3 and Value3 < Value4));


LongExitSignal = false;


ShortExitSignal = false;




                
//------------------------------------------------------------------
// Rule: Long entry
//------------------------------------------------------------------
if LongEntrySignal

then begin
	// Action #1
	if(OpenOrdersAllowed) then begin         
		IntPriceLevelLong = Round2Fraction((SQ_ParabolicSAR(0.02, 0.20)[1] + (PriceEntryMult1 * SQ_BarRange[0])));
		
		If not LimitMaxDistanceFromMarket or Round(absvalue(IntPriceLevelLong - CurrentAsk) / CurrentAsk * 100, 2) <= MaxDistancePct Then begin
			NumberOfSharesLong = mmLots * mmMultiplier;
			If NumberOfSharesLong > 0 Then begin
				if(MarketPosition = 0) then  begin
					Buy NumberOfSharesLong shares next bar at IntPriceLevelLong stop;
			
					If UseInitialStopLoss Then begin
                  IntLongSL = SQ_ConvertToPips(Absvalue( - StopLoss1 * tickSize));
                  If MinimumSL > 0 and IntLongSL < MinimumSL Then IntLongSL = MinimumSL;
                  If MaximumSL > 0 and IntLongSL > MaximumSL Then IntLongSL = MaximumSL;

                  If IntLongSL > 0 Then begin
                     SetStopContract;
                     SetStopLoss((MinMove / PriceScale) * BigPointValue * IntLongSL);
                  end;
                  IntPT = SQ_ConvertToPips(Absvalue( + ProfitTarget1 * tickSize));
                  If MinimumPT > 0 and IntPT < MinimumPT Then IntPT = MinimumPT;
                  If MaximumPT > 0 and IntPT > MaximumPT Then IntPT = MaximumPT;

                  If IntPT > 0 Then begin
                     SetStopContract;
                     SetProfitTarget((MinMove / PriceScale) * BigPointValue * IntPT);
                  end;
					end;
				end;
			end;
		end;
	end;

end;

//------------------------
// Orders Exits (SL, PT, Trailing) for Rule: Long entry 
//------------------------
if(MarketPosition > 0) then begin

	LongSLPlaced = false;

	If BarsSinceEntry(0) = 0 then begin
		IntLongSL = 0;
		IntLongTS = 0;
		IntLongBE = 0;
	end;

	// StopLoss
	IntLongSL = EntryPrice - StopLoss1 * tickSize;
	IntLongSL = SQ_CorrectMinMaxSLPT(IntLongSL, MinimumSL, MaximumSL, true);
	If IntLongSL <> 0 Then begin
		Sell("LongSL") next bar at IntLongSL stop;
		LongSLPlaced = true;
	end Else IntLongSL = 0;

	// ProfitTarget init
	IntPT = EntryPrice + ProfitTarget1 * tickSize;
	IntPT = SQ_CorrectMinMaxSLPT(IntPT, MinimumPT, MaximumPT, false);
	If IntPT < 0 Then IntPT = 0;
		
	If IntPT <> 0 then begin 
		Sell next bar at IntPT limit;
	end;
		
	if LongSLPlaced = false and IntLongSL > 0 then begin
		// no SL activated this bar, use default one - handling if there is no SL, only Trailing stop or Move2BE
		Sell next bar at IntLongSL stop;
	end;	
end;

                
//------------------------------------------------------------------
// Rule: Short entry
//------------------------------------------------------------------
if (ShortEntrySignal and (LongEntrySignal = false))

then begin
	// Action #1
	if(OpenOrdersAllowed) then begin         
		IntPriceLevelShort = Round2Fraction((SQ_ParabolicSAR(0.02, 0.2)[1] - (PriceEntryMult1 * SQ_BarRange[0])));
		
		If not LimitMaxDistanceFromMarket or Round(absvalue(IntPriceLevelShort - CurrentBid) / CurrentBid * 100, 2) <= MaxDistancePct Then begin
			NumberOfSharesShort = mmLots * mmMultiplier;
			If NumberOfSharesShort > 0 Then begin
				if(MarketPosition = 0) then  begin
					SellShort NumberOfSharesShort shares next bar at IntPriceLevelShort stop;
			
					If UseInitialStopLoss Then begin
                  IntShortSL = SQ_ConvertToPips(Absvalue( + StopLoss1 * tickSize));
                  If MinimumSL > 0 and IntShortSL < MinimumSL Then IntShortSL = MinimumSL;
                  If MaximumSL > 0 and IntShortSL > MaximumSL Then IntShortSL = MaximumSL;

                  If IntShortSL > 0 Then begin
                     SetStopContract;
                     SetStopLoss((MinMove / PriceScale) * BigPointValue * IntShortSL);
                  end;
                  IntPT = SQ_ConvertToPips(Absvalue( - ProfitTarget1 * tickSize));
                  If MinimumPT > 0 and IntPT < MinimumPT Then IntPT = MinimumPT;
                  If MaximumPT > 0 and IntPT > MaximumPT Then IntPT = MaximumPT;

                  If IntPT > 0 Then begin
                     SetStopContract;
                     SetProfitTarget((MinMove / PriceScale) * BigPointValue * IntPT);
                  end;
					end;
				end;
			end;
		end;
	end;

end;

//------------------------
// Orders Exits (SL, PT, Trailing) for Rule: Short entry 
//------------------------
if(MarketPosition < 0) then begin

	ShortSLPlaced = false;

	If BarsSinceEntry(0) = 0 then begin
		IntShortSL = 0;
		IntShortTS = 0;
		IntShortBE = 0;
	end;

	// StopLoss
	IntShortSL = EntryPrice + StopLoss1 * tickSize;
	IntShortSL = SQ_CorrectMinMaxSLPT(IntShortSL, MinimumSL, MaximumSL, true);
	If IntShortSL <> 0 Then begin
		BuyToCover("ShortSL") next bar at IntShortSL stop;
		ShortSLPlaced = true;
	end Else IntShortSL = 0;

	// ProfitTarget init
	IntPT = EntryPrice - ProfitTarget1 * tickSize;
	IntPT = SQ_CorrectMinMaxSLPT(IntPT, MinimumPT, MaximumPT, false);
	If IntPT < 0 Then IntPT = 0;
		
	If IntPT <> 0 then begin 
		BuyToCover next bar at IntPT limit;
	end;
		
	if ShortSLPlaced = false and IntShortSL > 0 then begin
		// no SL activated this bar, use default one - handling if there is no SL, only Trailing stop or Move2BE
		BuyToCover next bar at IntShortSL stop;
	end;	
end;

                
//------------------------------------------------------------------
// Rule: Long exit
//------------------------------------------------------------------
if ((LongExitSignal and (LongEntrySignal = false)) and (MarketPosition > 0))

then begin
	// Action #1
	Sell("ClosePositionLong") next bar at market;
end;


                
//------------------------------------------------------------------
// Rule: Short exit
//------------------------------------------------------------------
if ((ShortExitSignal and (ShortEntrySignal = false)) and (MarketPosition < 0))

then begin
	// Action #1
	BuyToCover("ClosePositionShort") next bar at market;
end;


                



